% Simple function to create a MYSQL table with parameters defined here

function nil = CreateTable(tablename)

% might want schema in params
% might want to have multiple possibilities for table creation

cmd =[...
    'CREATE TABLE ',tablename,' ('...
    'date     DATE default NULL,',...
    'open     DECIMAL(10,3) NOT NULL,',...
    'close    DECIMAL(10,3) NOT NULL,',...
    'adjclose DECIMAL(10,3) NOT NULL,',...
    '52_low   DECIMAL(10,3) NOT NULL DEFAULT 0,'...
    '52_high  DECIMAL(10,3) NOT NULL DEFAULT 0,',...
    '50_day_average DECIMAL(10,3) NOT NULL DEFAULT 0,',...
    '200_day_average DECIMAL(10,3) NOT NULL DEFAULT 0)'
    ];

mysql(cmd)






end

