% Function to put lots of Database Select statements.
% The goal is to keep SQL logic out of the application logic as much as
% possible.
% In addition, these statemnts should be eventually ported to MySQL
% stored procedures for speed purposes. Oh well, for later.

function output = DB_Select(type,spec,condition)


switch strrep(upper(type),'_',' ')
    % Simplest one, get "Filled To" date for a given ticker
    case 'FILLED TO'
        cmd = [...
            'SELECT Filled_To FROM status WHERE( Ticker = "',spec,'")'
            ];
    case 'ANALYZED TO'
        cmd = [...
            'SELECT Analyzed_To FROM status WHERE( Ticker = "',spec,'")'
            ];
    case 'COUNT'
        cmd = [...
            'SELECT COUNT(*) FROM ',spec ...
            ];
    case '50AVG'
        cmd = [...
            'SELECT SUM(close)/count(*) FROM ',...
            spec,' WHERE(',...
            'date <= "',condition,'" and ',...
            'date >= SUBDATE("',condition,'",INTERVAL 50 DAY))'...
            ];
    case '200AVG'
        cmd = [...
            'SELECT SUM(close)/count(*) FROM ',...
            spec,' WHERE(',...
            'date <= "',condition,'" and ',...
            'date >= SUBDATE("',condition,'",INTERVAL 200 DAY))'...
            ];
    case '52MAX'
        cmd = [...
            'SELECT MAX(close) FROM ',...
            spec,' WHERE(',...
            'date <= "',condition,'" and ',...
            'date >= SUBDATE("',condition,'",INTERVAL 52 WEEK))'...
            ];
    case '52MIN'
        cmd = [...
            'SELECT MIN(close) FROM ',...
            spec,' WHERE(',...
            'date <= "',condition,'" and ',...
            'date >= SUBDATE("',condition,'",INTERVAL 52 WEEK))'...
            ];
    otherwise
        fprintf(2,'SNAP!, Unknown Database Selection Request!\n')
        dbstack(2,'-completenames')
        
end

output = mysql(cmd);




end











