function status = CREATE_MYSQL_TABLE(table_name)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
%       $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
%       $$$$    Written by Zach Dischner on  / /2011     $$$$
%       $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
%
%     Function  :
%
%     Purpose   :
%
%     Input     :
%
%     Output    :
%
%     Procedure :
%
%
%
%
%
%
%
%
%
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%% First one, create company_list

existing_tables = mysql('SHOW TABLES')';

if isfield(cell2struct(existing_tables(:),existing_tables(:)),table_name );  % struct of tables, with same fieldnames,
    disp(['A table named  ',table_name,'  Already exists. Overwrite?']);
    drop = input('Y or N \n','s');
    if drop == 'Y' | 'y';
        mysql(['DROP TABLE IF EXISTS ',table_name]);
    else return
    end
    
end

% Now, edit/refine the CREATE TABLE statements to refine the table choice
switch table_name
    case 'company_list'
        cmd=[...
            'CREATE TABLE company_list (id bigint(20) unsigned NOT NULL auto_increment,',...
            'ticker VARCHAR(6) NOT NULL,',...
            'Last_update DATETIME default NULL,',...
            'PRIMARY KEY(id));'...
            ]
        mysql(cmd)
    case 'EOD'
        cmd =[...
            'CREATE TABLE EOD (id bigint(20) unsigned NOT NULL,',...
            'date DATETIME default NULL,',...
            'EOD_price DECIMAL(10,3),',...
            '52_low DECIMAL(10,3),52_high DECIMAL(10,3),',...
            '50_day_average DECIMAL(10,3),',...
            '200_day_average DECIMAL(10,3),'...
            'KEY id (id))']
        mysql(cmd)
    case 'update_info'
        cmd = [...
            'CREATE TABLE update_info (last_date DATETIME default NULL)'...
            ]
        % we only update this table from here on, so insert a dummy
        % variable, CURDATE()
        mysql(cmd);
        mysql('insert into stocks.update_info (last_date) values (''2008-01-01'')')  % my arbritrary starting point,
        
    case 'current_stats'   % Current stats for each ticker, each days stats are stored in EOD
        cmd = [...
            'CREATE TABLE current_stats (id bigint(20) unsigned NOT NULL,',...
            'ticker VARCHAR(6) NOT NULL,',...
            '52_low DECIMAL(10,3),52_high DECIMAL(10,3),',...
            '50_day_average DECIMAL(10,3),',...
            '200_day_average DECIMAL(10,3),',...
            'Current_trend VARCHAR(200),',...
            'Current_percent DECIMAL(10,3),',...
            'Average_up DECIMAL(10,3),',...
            'Average_down DECIMAL(10,3),',...
            'KEY ID (id), UNIQUE (id,ticker))']
        mysql(cmd)
        
        
        
        
    case 'all'
        mysql('DROP TABLE IF EXISTS company_list')
        cmd=[...
            'CREATE TABLE company_list (id bigint(20) unsigned NOT NULL auto_increment,',...
            'ticker VARCHAR(6) NOT NULL,',...
            'PRIMARY KEY(id));'...
            ]
        mysql(cmd)
        
        mysql('DROP TABLE IF EXISTS EOD')
        cmd =[...
            'CREATE TABLE EOD (id bigint(20) unsigned NOT NULL,',...
            'date DATE default NULL,',...
            'EOD_price DECIMAL(10,3) NOT NULL,',...
            '52_low DECIMAL(10,3) NOT NULL DEFAULT 0,52_high DECIMAL(10,3) NOT NULL DEFAULT 0,',...
            '50_day_average DECIMAL(10,3) NOT NULL DEFAULT 0,',...
            '200_day_average DECIMAL(10,3) NOT NULL DEFAULT 0,'...
            'KEY id (id))']
        mysql(cmd)
        
        mysql('DROP TABLE IF EXISTS update_info')
        cmd = [...
            'CREATE TABLE update_info (id bigint(20) unsigned NOT NULL,',...
            'last_date DATE default NULL,',...
            'start_date DATE default NULL, ',...
            'KEY id (id))']
        
        mysql(cmd);
        
       % mysql('insert into stocks.update_info (last_date) values (''2008-01-01'')')  % my arbritrary starting point,
        
        mysql('DROP TABLE IF EXISTS current_stats')
        cmd = [...
            'CREATE TABLE current_stats (id bigint(20) unsigned NOT NULL,',...
            'ticker VARCHAR(6) NOT NULL,',...
            '52_low DECIMAL(10,3) NOT NULL,52_high DECIMAL(10,3) NOT NULL,',...
            '50_day_average DECIMAL(10,3) NOT NULL,',...
            '200_day_average DECIMAL(10,3) NOT NULL,'...
            'KEY ID (id),UNIQUE (id,ticker))']
        mysql(cmd)  
        
        
    otherwise
        disp(['Table creation for ',table_name,' not yet defined'])
end




end